### PR TITLE
Create remove-query-string.php

### PR DESCRIPTION
**Pull request by chinmayrajyaguru**
If you will test website speed then you can notice that your Bootstrap users not getting speed benefit. This must be added because you're using CDN so resources with a "?" in the URL are not cached by some proxy caching servers.
Test your #b4st here: https://tools.pingdom.com

Thank you!

### CODE REVIEW

**Comment by chinmayrajyaguru** [comment]
Sir, you have updated (called) remove-query-string.php in function.php but maybe forget to add this pull request in written functions/remove-query-string.php file.

Please take action earlier.
Thank you @SimonPadbury

**Comment by SimonPadbury** [comment]
Hello Sir Chinmay,

OK, I have created the file now.

(Previously, I thought you created it. Now I see that you created it in your branch.)

Thankyou.

**Comment by dostrog** [comment]
First line has '#' symbol and file does not have '<?php'. Is it OK?
My test site does not run functions from your file just echoed its content.

**Comment by SimonPadbury** [comment]
Thankyou Sergey,

Resolved.

**Pull request merged**
